import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";
import { Card } from "@/components/ui/card";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [{ title: "Terms & Conditions — Upriter" }] }),
  component: () => (
    <AppShell title="Terms & Conditions" subtitle="Last updated: June 2026">
      <Card className="p-6 max-w-3xl space-y-4 text-sm">
        <Section title="1. Service">Upriter is a patient flow and queue management platform. It provides token bookings, queue updates and journey timing recommendations. It is not a substitute for professional medical advice.</Section>
        <Section title="2. Accounts">You confirm the information you provide during onboarding is accurate. Each account is for personal use.</Section>
        <Section title="3. No booking fees">Hospital registration on Upriter is free. There are no booking fees charged to patients.</Section>
        <Section title="4. AI recommendations">Risk assessments and arrival times are generated by AI to assist — not diagnose. Final decisions rest with treating clinicians and reception staff.</Section>
        <Section title="5. Emergencies">In any emergency, dial 108 or visit the nearest emergency department immediately.</Section>
        <Section title="6. Liability">Upriter is provided "as is". To the extent permitted by law, we are not liable for indirect damages or missed appointments due to network, device or hospital factors outside our control.</Section>
        <Section title="7. Changes">We may update these terms; we'll notify you in-app.</Section>
      </Card>
    </AppShell>
  ),
});

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="font-semibold">{title}</h3>
      <p className="text-muted-foreground mt-1">{children}</p>
    </div>
  );
}
